src/travel_app/database/models/country.py
"""This module contains the model class for the country information
table.

Author(s): Thomas,
"""
from flask import Flask

from database.database import _db


class Country(_db.Model):
    """Model class for country information.

    Fields:
    id -- The id of the country (primary key)
    name -- The name of the country
    description -- Information about the country.
    travel_advice -- The summary of the travel advice (whether the
        country should be travelled to)
    crime_index -- The level of crime in the country (higher means
        more crime)
    disaster_risk -- The severity and risk of disasters that happen in
        said country (higher means worse disasters)
    corrpution_index -- How corrupt a country is (higher means more)
    health -- The level of healthcare in the country (higher means
        better)
    """
    __tablename__ = "countries"
    id = _db.Column(_db.Integer, primary_key=True, autoincrement=True)
    name = _db.Column(_db.String(64), nullable=False)
    description = _db.Column(_db.String(2048), nullable=False)
    travel_advice = _db.Column(_db.String(256), nullable=False)
    crime_index = _db.Column(_db.Float, default=0.0)
    disaster_risk = _db.Column(_db.Float, default=0.0)
    corruption_index = _db.Column(_db.Float, default=0.0)
    health = _db.Column(_db.Float, default=0.0)

    def __eq__(self, other):
        assert isinstance(other, Country)
        return self.id == other.id

    def __hash__(self):
        return self.id
        
    def __repr__(self):
        return f"Country <{self.name}>"


def all_country_names() -> list[str]:
    """Fetch all the country names from the database.

    Must be ran within app context.

    Returns a list of strings containing every name.
    """
    results = Country.query.all()
    if results:
        results = [country.name for country in Country.query.all()]
    return results


def get_country_by_name(name: str) -> Country:
    """Fetch the country from the database with the given name.

    Must be ran within app context.

    Parameters:
        name - string representing the name of the country

    Returns the country object if one was found, otherwise None.
    """
    result = Country.query.filter_by(name=name).first()
    return result


def get_all_countries() -> set:
    """Fetch all the countries from the database.

    Returns:
        Returns all the countries as part of a set.
    """
    return set(Country.query.all())

  
def remove_country(country: Country):
    """Removes a country from the database.

    Must be ran within app context.
    Checks country is in the database before attempting removal.
    Also deletes all user votes and country advice alongside it.

    Parameters:
        country - the country to remove
    """
    # Check country in db before continuing.
    in_db = Country.query.filter_by(id=country.id) != None
    if not in_db:
        return

    # Remove all user votes.
    from database.models.uservotes import get_all_votes, remove_vote
    for vote in get_all_votes(country):
        remove_vote(vote)

    # Remove all country advice.
    from database.models.countryadvice import get_advice, remove_country_advice
    for advice in get_advice(country):
        remove_country_advice(country, advice)

    # Remove country.
    _db.session.delete(country)
    _db.session.commit()


def add_country(country: Country):
    """Adds a country to the database.

    Must be ran within app context.
    There is no checking if a country exists. The primary key is the
    id of the country. Two separate countries with the same name can
    exist.

    Parameters:
        country - the country to add
    """
    _db.session.add(country)
    _db.session.commit()

src/travel_app/main/views.py
from werkzeug.security import generate_password_hash, check_password_hash
from users.forms import *
from database.database import get_database
from database.models.country import get_country_by_name
from database.models import uservotes as uv
from database.models import user as u
from flask import Blueprint, render_template, abort, flash, redirect, url_for, request, get_flashed_messages
from flask_login import login_user, logout_user, login_required, current_user
from session import role_required

main_blueprint = Blueprint('main', __name__, template_folder='templates')
map_blueprint = Blueprint('map', __name__, template_folder='templates')
admin_blueprint = Blueprint('admin', __name__, template_folder='templates')
country_blueprint = Blueprint('country', __name__, template_folder='templates')
search_blueprint = Blueprint('search', __name__, template_folder='templates')
login_blueprint = Blueprint('login', __name__, template_folder='templates')
register_blueprint = Blueprint('register', __name__, template_folder='templates')

isSearch = True
country = None

@main_blueprint.route('/')
def index():
    return render_template('main/homepage.html')


@map_blueprint.route('/map')
def map():
    return render_template('main/map.html')


@admin_blueprint.route('/admin', methods=['GET', 'POST'])
@login_required
@role_required('admin')
def admin():
    global isSearch
    global country

    search_form = SearchForm()
    country_form = CountryForm()

    # Render the search form if in search mode.
    if isSearch:
        # Search for the country.
        if search_form.validate_on_submit():
            country = get_country_by_name(search_form.search.data.lower())

            # If no country was found, render search bar.
            if not country:
                return render_template(
                    'main/admin.html',
                    search_form=search_form,
                    country_form=None
                )

            isSearch = False
            country_form.name.data = country.name
            country_form.description.data = country.description
            country_form.travel_advice.data = country.travel_advice
            country_form.crime_index.data = country.crime_index
            country_form.disaster_risk.data = country.disaster_risk
            country_form.corruption_index.data = country.corruption_index
            country_form.health.data = country.health

            return render_template(
                "main/admin.html",
                search_form=None,
                country_form=country_form)
        else:
            return render_template(
                'main/admin.html',
                search_form=search_form,
                country_form=None)

    # If in edit mode.
    else:
        if country_form.validate_on_submit():
            country.name = country_form.name.data,
            country.description = country_form.description.data,
            country.travel_advice = country_form.travel_advice.data,
            country.crime_index = country_form.crime_index.data,
            country.disaster_risk = country_form.disaster_risk.data,
            country.corruption_index = country_form.corruption_index.data,
            country.health = country_form.health.data
            get_database().session.merge(country)
            get_database().session.commit()
            isSearch = True

            return render_template(
                "main/admin.html",
                search_form=search_form,
                country_form=None)
        else:
            return render_template(
                "main/admin.html",
                search_form=None,
                country_form=country_form)

                
@admin_blueprint.route('/country')
def country():
    return render_template('main/country.html')


@country_blueprint.route('/search', methods=['GET', 'POST'])
def search():
    """ Search for a country by name.
        If the country is not found, flash a message and return to the search page
        If the country is found, display the country information on the country page
    """
    form = SearchForm()
    if form.validate_on_submit():
        country = get_country_by_name(form.search.data.lower())
        if country is not None:
            return redirect(f"/country/{country.name}")
        flash(f'Country "{form.search.data}" not found. Please try again.', 'warning')
    return render_template('main/search.html', form=form)


@country_blueprint.route('/country/<country_name>')
def show_country(country_name):
    country = get_country_by_name(country_name)
    if country:
        upvotes = len(uv.get_votes(country, uv.VoteType.UPVOTE))
        downvotes = len(uv.get_votes(country, uv.VoteType.DOWNVOTE))
        total_index = round((country.corruption_index + country.crime_index + country.health + country.disaster_risk) / 4, 4)
        return render_template('main/country.html',
                               **vars(country),
                               upvotes=upvotes,
                               downvotes=downvotes,
                               total_index= total_index)
    abort(404)


@login_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        if u.validate_user(username, password):
            login_user(u.get_user_by_name(username))
            flash(f'Logged in successfully.', 'success')
            return redirect(url_for('main.index'))
        else:
            flash('Login unsuccessful. Please check username and password.', 'warning')
    if form.errors:
        print(form.errors)
    return render_template('main/login.html', form=form)


@register_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        existing_user = u.get_user_by_name(username)
        if existing_user is not None:
            flash(f'Username "{username}" is already taken. Please try again.', 'warning')
            return render_template('main/register.html', form=form)
        else:
            new_user = u.User(username=username, password=password, role='guest')
            u.add_user(new_user)
            flash(f'Account created for {form.username.data}!', 'success')
            return redirect(url_for('login.login'))
    if form.errors:
        print(form.errors)
    return render_template('main/register.html', form=form)


@main_blueprint.route('/logout')
@login_required
def logout():
    logout_user()
    flash(f'Logged out successfully.', 'success')
    return redirect(url_for('main.index'))


@main_blueprint.route('/upvote', methods=['GET', 'POST'])
@login_required
def upvote():
    country_name = request.form.get('country_name')
    print(country_name)
    country = get_country_by_name(country_name)
    if country:
        user = u.get_user_by_name(current_user.username)
        if uv.get_user_vote(user, country) == None:
            new_vote = uv.UserVote()
            new_vote.country_id = country.id
            new_vote.user_id = current_user.id
            new_vote.vote_id = uv.VoteType.UPVOTE.value
            uv.add_vote(new_vote)
            flash(f"You have upvoted {country_name.capitalize()}'s information.", 'success')
            return redirect("/country/%s" % country_name)
        else:
            flash(f'You have already voted for {country_name.capitalize()}.', 'warning')
            return redirect("/country/%s" % country_name)
    else:
        abort(404)


@main_blueprint.route('/downvote', methods=['GET', 'POST'])
@login_required
def downvote():
    country_name = request.form.get('country_name')
    print(country_name)
    country = get_country_by_name(country_name)
    if country:
        user = u.get_user_by_name(current_user.username)
        if uv.get_user_vote(user, country) == None:
            new_vote = uv.UserVote()
            new_vote.country_id = country.id
            new_vote.user_id = current_user.id
            new_vote.vote_id = uv.VoteType.DOWNVOTE.value
            uv.add_vote(new_vote)
            flash(f"You have downvoted {country_name.capitalize()}'s information.", 'success')
            return redirect("/country/%s" % country_name)
        else:
            flash(f'You have already voted for {country_name.capitalize()}.', 'warning')
            return redirect("/country/%s" % country_name)
    else:
        abort(404)


@main_blueprint.route('/vote/reset', methods=['GET', 'POST'])
@login_required
def reset_vote():
    country_name = request.form.get('country_name')
    print(country_name)
    country = get_country_by_name(country_name)
    if country:
        user = u.get_user_by_name(current_user.username)
        vote = uv.get_user_vote(user, country)
        if vote != None:
            uv.remove_vote(vote)
            flash(f'You have removed your vote for {country_name.capitalize()}.', 'success')
            return redirect("/country/%s" % country_name)
        else:
            flash(f'You have not voted for {country_name.capitalize()}.', 'warning')
            return redirect("/country/%s" % country_name)
    else:
        abort(404)

src/travel_app/templates/main/admin.html
{% extends "base.html" %}

{% block barcontent %}
    <li><a href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a href="/search">Search</a></li>
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
{% block bodycontent %}
<div style="margin-left:15%;padding:1px 16px;">
    <h1 style="text-align: left">
        <span style="font-family:Pacifico">DestiKnow</span>
        <img align="right" src="/static/images/logo.png" width="80" height="80" align="right">
    </h1>

    {% if country_form %}
        <form method="POST">
            {{ country_form.csrf_token }}
            <p class="edit-form">Name: {{ country_form.name(size="64") }}</p>
            <p class="edit-form">Description: {{ country_form.description(rows="5", cols="128") }}</p>
            <p class="edit-form">Travel advice: {{ country_form.travel_advice(rows="5", cols="128") }}</p>
            <p class="edit-form">Crime index: {{ country_form.crime_index(size="10") }}</p>
            <p class="edit-form">Disaster risk: {{ country_form.disaster_risk(size="10") }}</p>
            <p class="edit-form">Corruption index: {{ country_form.corruption_index(size="10") }}</p>
            <p class="edit-form">Health index: {{ country_form.health(size="10") }}</p>
            <p class="edit-form">Save changes: {{ country_form.submit() }}</p>
        </form>
    {% else %}
        <form method="POST">
            {{ search_form.csrf_token }}
            {{ search_form.search() }}
            {{ search_form.submit() }}
        </form>
    {% endif %}
</div>
{% endblock %}

src/travel_app/templates/main/country.html
{% extends "base.html" %}
{% block stylecontent %}
    {% if 0.4 > total_index >= 0.2 %}
        .squaretotal{
           background-color: green;
        }
    {% elif 0.6 > total_index >= 0.4 %}
        .squaretotal{
           background-color: yellow;
        }
    {% elif 0.8 > total_index >= 0.6 %}
        .squaretotal{
           background-color: orange;
        }
    {% elif total_index >= 0.8 %}
        .squaretotal{
           background-color: red;
        }
    {% else %}
        .squaretotal{
           background-color: #00a8f3;
        }
    {% endif %}
    {% if 0.4 > crime_index >= 0.2 %}
        .squarecrime{
           background-color: green;
        }
    {% elif 0.6 > crime_index >= 0.4 %}
        .squarecrime{
           background-color: yellow;
        }
    {% elif 0.8 > crime_index >= 0.6 %}
        .squarecrime{
           background-color: orange;
        }
    {% elif crime_index >= 0.8 %}
        .squarecrime{
           background-color: red;
        }
    {% else %}
        .squarecrime{
           background-color: #00a8f3;
        }
    {% endif %}
        {% if 0.4 > disaster_risk >= 0.2 %}
        .squaredisaster{
           background-color: green;
        }
    {% elif 0.6 > disaster_risk >= 0.4 %}
        .squaredisaster{
           background-color: yellow;
        }
    {% elif 0.8 > disaster_risk >= 0.6 %}
        .squaredisaster{
           background-color: orange;
        }
    {% elif disaster_risk >= 0.8 %}
        .squaredisaster{
           background-color: red;
        }
    {% else %}
        .squaredisaster{
           background-color: #00a8f3;
        }
    {% endif %}
        {% if 0.4 > corruption_index >= 0.2 %}
        .squarecorruption{
           background-color: green;
        }
    {% elif 0.6 > corruption_index >= 0.4 %}
        .squarecorruption{
           background-color: yellow;
        }
    {% elif 0.8 > corruption_index >= 0.6 %}
        .squarecorruption{
           background-color: orange;
        }
    {% elif corruption_index >= 0.8 %}
        .squarecorruption{
           background-color: red;
        }
    {% else %}
        .squarecorruption{
           background-color: #00a8f3;
        }
    {% endif %}
    {% if 0.4 > health >= 0.2 %}
        .squarehealth{
           background-color: green;
        }
    {% elif 0.6 > health >= 0.4 %}
        .squarehealth{
           background-color: yellow;
        }
    {% elif 0.8 > health >= 0.6 %}
        .squarehealth{
           background-color: orange;
        }
    {% elif health >= 0.8 %}
        .squarehealth{
           background-color: red;
        }
    {% else %}
        .squarehealth{
            background-color: #00a8f3;
        }
    {% endif %}
{% endblock %}
{% block barcontent %}
    <li><a href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a href="/search">Search</a></li>
    <li><a href="/admin">Admin</a></li>
    {% if not current_user.is_authenticated %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}

{% endblock %}
{% block bodycontent %}
<div style="margin-left:15%;padding:1px 16px;text-align:left;text-transform: capitalize">
    <h1>{{ name }}</h1>
</div>
    </div>
    <div style="margin-left:35%;padding:1px 16px;width: 50%; display: table">
    <div style="width: 10%; display: table-cell">
        <div class="squaretotal" style="height: 90px; width: 90px">
            <div style="text-align: center; font-size: 12px;">Total</div>
            <div style="text-align: center; font-size: 14px; padding-top: 20%">{{ total_index }}</div>
        </div>
    </div>
    <div style="width: 10%; display: table-cell">
        <div class="squarecrime" style="height: 70px; width: 70px">
            <div style="text-align: center; font-size: 12px;">Crime</div>
            <div style="text-align: center; font-size: 14px; padding-top: 20%">{{ crime_index }}</div>
        </div>
    </div>
    <div style="width: 10%; display: table-cell">
        <div class="squaredisaster" style="height: 70px; width: 70px">
            <div style="text-align: center; font-size: 12px;">Disasters</div>
            <div style="text-align: center; font-size: 14px; padding-top: 20%">{{ disaster_risk }}</div>
        </div>
    </div>
    <div style="width: 10%; display: table-cell">
        <div class="squarecorruption" style="height: 70px; width: 70px">
            <div style="text-align: center; font-size: 12px;">Corruption</div>
            <div style="text-align: center; font-size: 14px; padding-top: 20%">{{ corruption_index }}</div>
        </div>
    </div>
    <div style="width: 10%; display: table-cell">
        <div class="squarehealth" style="height: 70px; width: 70px">
            <div style="text-align: center; font-size: 12px;">Healthcare</div>
            <div style="text-align: center; font-size: 14px; padding-top: 20%">{{ health }}</div>
        </div>
    </div>
</div>
<div style="margin-left:15%;padding:1px 16px;text-align:left">
    <h3>Country Description:</h3>
    <h5>{{ description }}</h5>
</div>
<div style="margin-left:15%;padding:1px 16px;text-align:left">
    <h3>Country Risk Advice:</h3>
    <h5>{{ travel_advice }}</h5>
</div>
<div style="margin-left:15%;padding:1px 16px;height:300px;text-align:center">
    <h3>Votes:</h3>
    <h5>Up Votes: {{ upvotes }}</h5>
    <h5>Down Votes: {{ downvotes }}</h5>
</div>
<div style="margin-left:15%;padding:1px 16px;width: 100%; display: table">
    <div style="display: table-row">
        <div style="width: 20%; display: table-cell">
			<form action="/upvote" method="post">
				<input type="hidden" name="country_name" value="{{ name }}">
				<button name="upvoteButton" type="submit">Upvote</button>
			</form>
			<form action="/downvote" method="post">
				<input type="hidden" name="country_name" value="{{ name }}">
				<button name="downvoteButton" type="submit">Downvote</button>
			</form>
			<form action="/vote/reset" method="post">
				<input type="hidden" name="country_name" value="{{ name }}">
				<button name="resetvoteButton" type="submit">Reset Vote</button>
			</form>
        </div>
    </div>
</div>
{% endblock %}

src/travel_app/templates/main/homepage.html
{% extends "base.html" %}

{% block barcontent %}
    <li><a class="active" href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a href="/search">Search</a></li>
    <li><a href="/admin">Admin</a></li>
    {% if not current_user.is_authenticated %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
<style>
</style>
{% block bodycontent %}

<div style="margin-left:15%;padding:1px 16px;">
    <h1 style="padding: 1px 0px 0px 80px">
        Welcome to <span style="font-family:Pacifico">DestiKnow</span><img src="/static/images/logo.png" width="80" height="80" align="right">
    </h1>
    <p class=description>
        Welcome to DestiKnow! Home of extensive travel information for 95% of the world. Use the <a href="/map" class=quicklink>map</a> to navigate the world or use the handy <a href="/search" class=quicklink>search</a> function if you can't find what you're looking for.
    </p>
    <a href="/map">
        <img src="/static/images/world.png" alt="map" height="400px" class="centre">
    </a>
</div>

{% endblock %}

src/travel_app/templates/main/login.html
{% extends "base.html" %}

{% block barcontent %}
    <li><a href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a href="/search">Search</a></li>
    <li><a href="/admin">Admin</a></li>
    {% if not current_user.is_authenticated %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
{% block bodycontent %}

<div style="margin-left:15%;padding:1px 16px;">
    <h1 style="text-align: left">
        <span style="font-family:Pacifico">DestiKnow</span>
        <img align="right" src="/static/images/logo.png" width="80" height="80" align="right">
    </h1>
    <h2>Login</h2>
</div>
<div style="margin-left:15%;padding:8px 16px;">
<form method="POST">
    {{ form.csrf_token }}
    {{ form.username.label }} {{ form.username() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.submit() }}
</form>
</div>

{% endblock %}

src/travel_app/templates/main/register.html
{% extends "base.html" %}

{% block barcontent %}
    <li><a href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a href="/search">Search</a></li>
    <li><a href="/admin">Admin</a></li>
    {% if not current_user.is_authenticated %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
{% block bodycontent %}

<div style="margin-left:15%;padding:1px 16px;">
    <h1 style="text-align: left">
        <span style="font-family:Pacifico">DestiKnow</span>
        <img align="right" src="/static/images/logo.png" width="80" height="80" align="right">
    </h1>
    <h2>Register</h2>
</div>
<div style="margin-left:15%;padding:8px 16px;">
<form method="POST">
    {{ form.csrf_token }}
    {{ form.username.label }} {{ form.username() }}
    {{ form.password.label }} {{ form.password() }}
    {{ form.confirm_password.label }} {{ form.confirm_password() }}
    {{ form.submit() }}
</form>
</div>

{% endblock %}

src/travel_app/templates/main/search.html
{% extends "base.html" %}

{% block barcontent %}
    <li><a href="/">Home</a></li>
    <li><a href="/map">Map</a></li>
    <li><a class="active" href="/search">Search</a></li>
    <li><a href="/admin">Admin</a></li>
    {% if not current_user.is_authenticated %}
        <li><a href="/login">Login</a></li>
        <li><a href="/register">Register</a></li>
    {% endif %}
    {% if current_user.is_authenticated %}
        <li><a href="/logout">Logout</a></li>
    {% endif %}
{% endblock %}
{% block bodycontent %}

<center>
<div style="margin-left:15%;padding:1px 16px;">
    <h1 style="text-align: left">
        <span style="font-family:Pacifico">DestiKnow</span>
        <img align="right" src="/static/images/logo.png" width="80" height="80" align="right">
    </h1>
    <h2>Search</h2>
</div>
<div style="margin-left:15%;padding:8px 16px;">
<form method="POST" action="{{ url_for('country.search') }}">
    {{ form.csrf_token }}
    {{ form.search.label }} {{ form.search() }}
    {{ form.submit() }}
</form>
</div>
</center>

{% endblock %}